Check availability of qmake and version of Qt (minimum required: 4.2)
git-svn-id: file:///Users/tack/GecodeGitMigration/gecode-svn-mirror/gecode/trunk@5458 e85b7adc-8362-4630-8c63-7469d557c915

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -731,6 +731,7 @@ ENABLEDOCCHM
 enable_set_vars
 enable_cpltset_vars
 enable_int_vars
+QMAKE
 QTINCLUDES
 QTDEFINES
 QTLIBS
@@ -9545,6 +9546,64 @@ echo "${ECHO_T}yes" >&6; }
 _ACEOF
 
 
+    # Extract the first word of "qmake", so it can be a program name with args.
+set dummy qmake; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_QMAKE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$QMAKE"; then
+  ac_cv_prog_QMAKE="$QMAKE" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_QMAKE="found"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+QMAKE=$ac_cv_prog_QMAKE
+if test -n "$QMAKE"; then
+  { echo "$as_me:$LINENO: result: $QMAKE" >&5
+echo "${ECHO_T}$QMAKE" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+    if test "${QMAKE}x" = "x"; then
+      { { echo "$as_me:$LINENO: error: The qmake tool was not found." >&5
+echo "$as_me: error: The qmake tool was not found." >&2;}
+   { (exit 1); exit 1; }; }
+    else
+      ac_gecode_qt_version=`qmake -query QT_VERSION`
+      ac_gecode_qt_major=`echo ${ac_gecode_qt_version} | grep -o '^[0-9]*'`
+      ac_gecode_qt_minor=`echo ${ac_gecode_qt_version} | sed -e 's/^[0-9]*\\.//g' -e 's/\\.[0-9]*$//g'`
+      ac_gecode_qt_ok="yes"
+      if test ${ac_gecode_qt_major} -lt 4; then ac_gecode_qt_ok="no";
+      else if test ${ac_gecode_qt_major} -eq 4 \
+                -a ${ac_gecode_qt_minor} -lt 2; then ac_gecode_qt_ok="no";
+           fi
+      fi
+      if test "${ac_gecode_qt_ok}" != "yes"; then
+        { { echo "$as_me:$LINENO: error: Your version of Qt is too old. Minimum required: 4.2. Your version: ${ac_gecode_qt_version}." >&5
+echo "$as_me: error: Your version of Qt is too old. Minimum required: 4.2. Your version: ${ac_gecode_qt_version}." >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+    fi
+
         ac_gecode_gist_tmpdir=`mktemp -d gistqt.XXXXXX` || exit 1
     cd ${ac_gecode_gist_tmpdir}
     touch a.pro
@@ -10503,6 +10562,7 @@ ENABLEDOCCHM!$ENABLEDOCCHM$ac_delim
 enable_set_vars!$enable_set_vars$ac_delim
 enable_cpltset_vars!$enable_cpltset_vars$ac_delim
 enable_int_vars!$enable_int_vars$ac_delim
+QMAKE!$QMAKE$ac_delim
 QTINCLUDES!$QTINCLUDES$ac_delim
 QTDEFINES!$QTDEFINES$ac_delim
 QTLIBS!$QTLIBS$ac_delim
@@ -10521,7 +10581,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 34; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 35; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
