Enable static libs when building Mac framework
git-svn-id: file:///Users/tack/GecodeGitMigration/gecode-svn-mirror/gecode/trunk@9705 e85b7adc-8362-4630-8c63-7469d557c915

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -671,10 +671,10 @@ PROG_MAKE
 PROG_SED
 PROG_PERL
 CXXCPP
-BUILDSTATIC
-BUILDDLL
 USERSUFFIX
 BUILD_MACOS_FRAMEWORK
+BUILDSTATIC
+BUILDDLL
 DEBUG_BUILD
 CPP
 GREP
@@ -1345,9 +1345,9 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-framework      build framework bundle on Mac OS X [default=no]
   --enable-static         build static libraries [default=no]
   --enable-shared         build shared libraries [default=yes]
-  --enable-framework      build framework bundle on Mac OS X [default=no]
   --enable-debug          build with assertions [default=no]
   --enable-leak-debug     build with support for finding memory leaks
                           [default=no]
@@ -4745,59 +4745,6 @@ echo "${ECHO_T}no" >&6; }
   fi
 
 
-if test "${host_os}" = "windows" -a \
-                  "${ac_gecode_compiler_vendor}" = "gnu"; then
-            enable_static="yes"
-	    enable_shared="no"
-          fi
-          # Check whether --enable-static was given.
-if test "${enable_static+set}" = set; then
-  enableval=$enable_static;
-fi
-
-	  { echo "$as_me:$LINENO: checking whether to build static libraries" >&5
-echo $ECHO_N "checking whether to build static libraries... $ECHO_C" >&6; }
- 	  if test "${enable_static:-no}" = "yes"; then
-
-cat >>confdefs.h <<\_ACEOF
-#define GECODE_STATIC_LIBS
-_ACEOF
-
- 	     BUILDSTATIC="yes"
-
- 	     { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
- 	  else
- 	     BUILDSTATIC="no"
-
- 	     { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
- 	  fi
-	  # Check whether --enable-shared was given.
-if test "${enable_shared+set}" = set; then
-  enableval=$enable_shared;
-fi
-
-	  { echo "$as_me:$LINENO: checking whether to build shared libraries" >&5
-echo $ECHO_N "checking whether to build shared libraries... $ECHO_C" >&6; }
- 	  if test "${enable_shared:-yes}" = "yes"; then
- 	     BUILDDLL="yes"
-
- 	     { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
- 	  else
- 	     BUILDDLL="no"
-
- 	     if test "${enable_static:-no}" = "no"; then
- 	       { { echo "$as_me:$LINENO: error: One of --enable-static or --enable-shared must be given" >&5
-echo "$as_me: error: One of --enable-static or --enable-shared must be given" >&2;}
-   { (exit 1); exit 1; }; }
- 	     fi
- 	     { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
- 	  fi
-
-
 
 
 # Check whether --with-lib-prefix was given.
@@ -4862,12 +4809,8 @@ echo $ECHO_N "checking whether to build framework bundle on Mac OS X... $ECHO_C"
 echo "${ECHO_T}yes" >&6; }
       BUILD_MACOS_FRAMEWORK="yes"
 
-      cat >>confdefs.h <<\_ACEOF
-#define GECODE_STATIC_LIBS 1
-_ACEOF
-
-      BUILDSTATIC="yes"
-
+      enable_static="yes";
+      enable_shared="no";
     else
       { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
@@ -4875,6 +4818,59 @@ echo "${ECHO_T}no" >&6; }
 
     fi
   fi
+
+
+if test "${host_os}" = "windows" -a \
+                  "${ac_gecode_compiler_vendor}" = "gnu"; then
+            enable_static="yes"
+	    enable_shared="no"
+          fi
+          # Check whether --enable-static was given.
+if test "${enable_static+set}" = set; then
+  enableval=$enable_static;
+fi
+
+	  { echo "$as_me:$LINENO: checking whether to build static libraries" >&5
+echo $ECHO_N "checking whether to build static libraries... $ECHO_C" >&6; }
+ 	  if test "${enable_static:-no}" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define GECODE_STATIC_LIBS
+_ACEOF
+
+ 	     BUILDSTATIC="yes"
+
+ 	     { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+ 	  else
+ 	     BUILDSTATIC="no"
+
+ 	     { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+ 	  fi
+	  # Check whether --enable-shared was given.
+if test "${enable_shared+set}" = set; then
+  enableval=$enable_shared;
+fi
+
+	  { echo "$as_me:$LINENO: checking whether to build shared libraries" >&5
+echo $ECHO_N "checking whether to build shared libraries... $ECHO_C" >&6; }
+ 	  if test "${enable_shared:-yes}" = "yes"; then
+ 	     BUILDDLL="yes"
+
+ 	     { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+ 	  else
+ 	     BUILDDLL="no"
+
+ 	     if test "${enable_static:-no}" = "no"; then
+ 	       { { echo "$as_me:$LINENO: error: One of --enable-static or --enable-shared must be given" >&5
+echo "$as_me: error: One of --enable-static or --enable-shared must be given" >&2;}
+   { (exit 1); exit 1; }; }
+ 	     fi
+ 	     { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+ 	  fi
 
 
 # Check whether --enable-debug was given.
@@ -6157,7 +6153,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -6178,7 +6174,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -14377,10 +14373,10 @@ PROG_MAKE!$PROG_MAKE$ac_delim
 PROG_SED!$PROG_SED$ac_delim
 PROG_PERL!$PROG_PERL$ac_delim
 CXXCPP!$CXXCPP$ac_delim
-BUILDSTATIC!$BUILDSTATIC$ac_delim
-BUILDDLL!$BUILDDLL$ac_delim
 USERSUFFIX!$USERSUFFIX$ac_delim
 BUILD_MACOS_FRAMEWORK!$BUILD_MACOS_FRAMEWORK$ac_delim
+BUILDSTATIC!$BUILDSTATIC$ac_delim
+BUILDDLL!$BUILDDLL$ac_delim
 DEBUG_BUILD!$DEBUG_BUILD$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
