Added configure option --enable-leak-debug. This causes the test suite to call mtrace(). You can set the environment variable MALLOC_TRACE to a filename that will contain memory (de)allocation information after running ./test/test. Then use the mtrace perl script to analyze the output. It will report if there were any memory leaks, which can then be debugged using e.g. valgrind.
git-svn-id: file:///Users/tack/GecodeGitMigration/gecode-svn-mirror/gecode/trunk@3270 e85b7adc-8362-4630-8c63-7469d557c915

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -861,6 +861,8 @@ Optional Features:
   --enable-static         build static libraries [default=no]
   --enable-shared         build shared libraries [default=yes]
   --enable-debug          build with assertions [default=no]
+  --enable-leak-debug     build with support for finding memory leaks
+                          [default=no]
   --enable-profile        build with profiling information [default=no]
   --enable-doc-dot        enable graphs in documentation [default=yes]
   --enable-doc-search     enable documentation search engine
@@ -2016,6 +2018,8 @@ fi
 
 
           ac_config_commands="$ac_config_commands vti.icc"
+
+
 
 
 
@@ -3357,6 +3361,88 @@ echo "${ECHO_T}yes" >&6
 	    echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
        	    CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-DNDEBUG"
+	 fi
+
+# Check whether --enable-leak-debug or --disable-leak-debug was given.
+if test "${enable_leak_debug+set}" = set; then
+  enableval="$enable_leak_debug"
+
+fi;
+	 echo "$as_me:$LINENO: checking whether to build with support for finding memory leaks" >&5
+echo $ECHO_N "checking whether to build with support for finding memory leaks... $ECHO_C" >&6
+	 if test "${enable_leak_debug:-no}" = "yes"; then
+	    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	    echo "$as_me:$LINENO: checking whether mtrace is declared" >&5
+echo $ECHO_N "checking whether mtrace is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl_mtrace+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <mcheck.h>
+
+int
+main ()
+{
+#ifndef mtrace
+  char *p = (char *) mtrace;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl_mtrace=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_decl_mtrace=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl_mtrace" >&5
+echo "${ECHO_T}$ac_cv_have_decl_mtrace" >&6
+if test $ac_cv_have_decl_mtrace = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define GECODE_HAVE_MTRACE 1
+_ACEOF
+
+else
+  { { echo "$as_me:$LINENO: error: mtrace not available." >&5
+echo "$as_me: error: mtrace not available." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+	 else
+	    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
 	 fi
 
 # Check whether --enable-profile or --disable-profile was given.
