Added a configure switch --enable-doc-dot. If enabled, this checks for presence of the dot tool (used for generating graphs in the documentation). This fixes bug #37
git-svn-id: file:///Users/tack/GecodeGitMigration/gecode-svn-mirror/gecode/trunk@3177 e85b7adc-8362-4630-8c63-7469d557c915

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -313,7 +313,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all "
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT RANLIB ac_ct_RANLIB PKGCONFIG ac_ct_PKGCONFIG HAVE_PKGCONFIG CXXCPP CC CFLAGS ac_ct_CC BUILDSTATIC BUILDDLL CPP EGREP DLLPATH need_soname DLLFLAGS DLLEXT SOSUFFIX SOLINKSUFFIX sharedlibdir WLSONAME docdir SBJEXT LIBEXT LIBPREFIX STATICLIBEXT MINUSLDIR LINKLIBDIR cygpathprefix COMPILEOBJ COMPILESBJ COMPILERIN EXAMPLES_EXTRA_CXXFLAGS INSTALLLIBS LINKPREFIX LINKSUFFIX LINKOUTPUT KERNEL SEARCH INT SET MM ENABLEDOCSEARCH GECODE_DOXYGEN_TAGFILE ENABLEDOCCHM enable_set_vars enable_int_vars enable_examples enable_minimodel enable_search subdirs PKG_CONFIG_CXXFLAGS VERSION LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT RANLIB ac_ct_RANLIB PKGCONFIG ac_ct_PKGCONFIG HAVE_PKGCONFIG CXXCPP CC CFLAGS ac_ct_CC BUILDSTATIC BUILDDLL CPP EGREP DLLPATH need_soname DLLFLAGS DLLEXT SOSUFFIX SOLINKSUFFIX sharedlibdir WLSONAME docdir SBJEXT LIBEXT LIBPREFIX STATICLIBEXT MINUSLDIR LINKLIBDIR cygpathprefix COMPILEOBJ COMPILESBJ COMPILERIN EXAMPLES_EXTRA_CXXFLAGS INSTALLLIBS LINKPREFIX LINKSUFFIX LINKOUTPUT KERNEL SEARCH INT SET MM DOT GECODE_DOXYGEN_DOT ENABLEDOCSEARCH GECODE_DOXYGEN_TAGFILE ENABLEDOCCHM enable_set_vars enable_int_vars enable_examples enable_minimodel enable_search subdirs PKG_CONFIG_CXXFLAGS VERSION LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -862,6 +862,7 @@ Optional Features:
   --enable-shared         build shared libraries [default=yes]
   --enable-debug          build with assertions [default=no]
   --enable-profile        build with profiling information [default=no]
+  --enable-doc-dot        enable graphs in documentation [default=yes]
   --enable-doc-search     enable documentation search engine
                           [default=no]
   --enable-doc-tagfile    generate doxygen tagfile [default=no]
@@ -6277,7 +6278,74 @@ echo "$as_me: error: Gecode currently only supports the GNU and Microsoft compil
 esac
 
 
-# Check whether --enable-doc-search or --disable-doc-search was given.
+   # Check whether --enable-doc-dot or --disable-doc-dot was given.
+if test "${enable_doc_dot+set}" = set; then
+  enableval="$enable_doc_dot"
+
+fi;
+   # Extract the first word of "dot", so it can be a program name with args.
+set dummy dot; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_DOT+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$DOT"; then
+  ac_cv_prog_DOT="$DOT" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_DOT="dot"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+DOT=$ac_cv_prog_DOT
+if test -n "$DOT"; then
+  echo "$as_me:$LINENO: result: $DOT" >&5
+echo "${ECHO_T}$DOT" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+   echo "$as_me:$LINENO: checking whether to enable graphs in the documentation" >&5
+echo $ECHO_N "checking whether to enable graphs in the documentation... $ECHO_C" >&6
+   if test "${enable_doc_dot:-yes}" = "yes"; then
+     if test x$DOT = x; then
+        if test x"${enable_doc_dot}" = x; then
+	  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+     	  GECODE_DOXYGEN_DOT=NO
+
+	else
+          { { echo "$as_me:$LINENO: error: you need the dot tool from graphviz to generate graphs in the documentation" >&5
+echo "$as_me: error: you need the dot tool from graphviz to generate graphs in the documentation" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+     else
+        echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	GECODE_DOXYGEN_DOT=YES
+
+     fi
+   else
+     echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+     GECODE_DOXYGEN_DOT=NO
+
+   fi
+
+   # Check whether --enable-doc-search or --disable-doc-search was given.
 if test "${enable_doc_search+set}" = set; then
   enableval="$enable_doc_search"
 
@@ -6593,10 +6661,9 @@ for ac_i in : $LIBOBJS; do test "x$ac_i" = x: && continue
   # 1. Remove the extension, and $U if already installed.
   ac_i=`echo "$ac_i" |
 	 sed 's/\$U\././;s/\.o$//;s/\.obj$//'`
-  # 2. Prepend LIBOBJDIR.  When used with automake>=1.10 LIBOBJDIR
-  #    will be set to the directory where LIBOBJS objects are built.
-  ac_libobjs="$ac_libobjs \${LIBOBJDIR}$ac_i\$U.$ac_objext"
-  ac_ltlibobjs="$ac_ltlibobjs \${LIBOBJDIR}$ac_i"'$U.lo'
+  # 2. Add them.
+  ac_libobjs="$ac_libobjs $ac_i\$U.$ac_objext"
+  ac_ltlibobjs="$ac_ltlibobjs $ac_i"'$U.lo'
 done
 LIBOBJS=$ac_libobjs
 
@@ -7188,6 +7255,8 @@ s,@SEARCH@,$SEARCH,;t t
 s,@INT@,$INT,;t t
 s,@SET@,$SET,;t t
 s,@MM@,$MM,;t t
+s,@DOT@,$DOT,;t t
+s,@GECODE_DOXYGEN_DOT@,$GECODE_DOXYGEN_DOT,;t t
 s,@ENABLEDOCSEARCH@,$ENABLEDOCSEARCH,;t t
 s,@GECODE_DOXYGEN_TAGFILE@,$GECODE_DOXYGEN_TAGFILE,;t t
 s,@ENABLEDOCCHM@,$ENABLEDOCCHM,;t t
