Changed configure options for creating universal binaries, allow for arbitrary architectures and macosx-version-min.
git-svn-id: file:///Users/tack/GecodeGitMigration/gecode-svn-mirror/gecode/trunk@6361 e85b7adc-8362-4630-8c63-7469d557c915

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1370,9 +1370,9 @@ Optional Packages:
   --with-compiler-vendor  Override compiler test. Valid values are gnu, intel,
                           and microsoft.
   --with-sdk              SDK to use on Mac OS X
-
   --with-macosx-version-min
-                          minimum supported version of Mac OS X
+                          minimum version of Mac OS X to support
+  --with-archiectures     architectures to compile for on Mac OS X
   --with-boost            path to the boost library (used for serialization)
 
 Some influential environment variables:
@@ -4112,12 +4112,6 @@ if test "${with_macosx_version_min+set}" = set; then
   withval=$with_macosx_version_min;
 fi
 
-
-# Check whether --with-macosx-version-min was given.
-if test "${with_macosx_version_min+set}" = set; then
-  withval=$with_macosx_version_min;
-fi
-
   if test "${host_os}" = "darwin"; then
     if test "${with_macosx_version_min:-no}" != "no"; then
       { echo "$as_me:$LINENO: checking whether ${CXX} accepts -mmacosx-version-min=${with_macosx_version_min}" >&5
@@ -4247,6 +4241,156 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
       DLLFLAGS="${DLLFLAGS}${DLLFLAGS:+ }-mmacosx-version-min=${with_macosx_version_min}"
     fi
+  fi
+
+# Check whether --with-architectures was given.
+if test "${with_architectures+set}" = set; then
+  withval=$with_architectures;
+fi
+
+  { echo "$as_me:$LINENO: checking Whether to build for different architectures" >&5
+echo $ECHO_N "checking Whether to build for different architectures... $ECHO_C" >&6; }
+  if test "${host_os}" = "darwin"; then
+    if test "${with_architectures:-no}" != "no"; then
+      archflags="";
+      for a in `echo ${with_architectures} | sed -e "s/,/ /g"`; do
+	archflags="${archflags} -arch $a";
+      done
+      { echo "$as_me:$LINENO: checking whether ${CXX} accepts ${archflags}" >&5
+echo $ECHO_N "checking whether ${CXX} accepts ${archflags}... $ECHO_C" >&6; }
+   ac_gecode_save_CXXFLAGS="${CXXFLAGS}"
+   CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }${archflags} -Werror"
+   ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+   cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+      CXXFLAGS="${ac_gecode_save_CXXFLAGS}"
+      CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }${archflags}"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+      CXXFLAGS="${ac_gecode_save_CXXFLAGS}"
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+   ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+   { echo "$as_me:$LINENO: checking whether ${CC} accepts ${archflags}" >&5
+echo $ECHO_N "checking whether ${CC} accepts ${archflags}... $ECHO_C" >&6; }
+   ac_gecode_save_CFLAGS="${CFLAGS}"
+   CFLAGS="${CFLAGS}${CFLAGS:+ }${archflags} -Werror"
+   ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+   cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+      CFLAGS="${ac_gecode_save_CFLAGS}"
+      CFLAGS="${CFLAGS}${CFLAGS:+ }${archflags}"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+      CFLAGS="${ac_gecode_save_CFLAGS}"
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+   ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+      DLLFLAGS="${DLLFLAGS}${DLLFLAGS:+ }${archflags}"
+      { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+    else
+      { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+    fi
+  else
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
   fi
 
 
